-- ============================================================
-- 010_seed_products.sql
-- Seeds all Line Coffee products exactly as they appear on the website.
-- Run AFTER 009_seed_categories.sql (categories must exist first).
-- Safe to re-run: ON CONFLICT (slug) DO UPDATE
-- ============================================================

-- ─── PRODUCTS ───────────────────────────────────────────────────────────────────

INSERT INTO public.products (
  slug, name_en, name_ar, description_en, description_ar,
  category_id, images, roast_level, flavor_notes,
  is_featured, is_best_seller, is_new, is_visible, stock_quantity
)
VALUES

-- ── Turkish Coffee ───────────────────────────────────────────────────────────────
('turkish-morning-strength','Morning Strength','قوة الصباح',
 'Strong robusta with light sweetness, high caffeine',
 'روبوستا قوي مع حلاوة خفيفة — كافيين عالي، مناسب لبداية يومك',
 (SELECT id FROM public.categories WHERE slug='turkish-coffee'),
 ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
 'dark',ARRAY['Robusta','Strong'],true,true,false,true,100),

('turkish-perfect-balance','Perfect Balance','التوازن المثالي',
 'Light floral notes with robusta body, great for hotels and cafés',
 'فلورال خفيف مع ثقل الروبوستا — مناسب للفنادق والكافيهات',
 (SELECT id FROM public.categories WHERE slug='turkish-coffee'),
 ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
 'medium',ARRAY['Floral','Balanced'],true,false,false,true,100),

('turkish-professional-clean','Professional Clean Cup','النظافة المحترفة',
 '65% arabica clean and consistent, clear chocolate notes',
 'أرابيكا 65% نظيف ومتسق — شوكولاتة واضحة',
 (SELECT id FROM public.categories WHERE slug='turkish-coffee'),
 ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
 'medium',ARRAY['Chocolate','Arabica'],false,false,false,true,100),

('turkish-premium','Turkish Premium','البريميوم',
 '90% arabica, true specialty floral-fruity profile',
 'أرابيكا 90% — specialty coffee حقيقية، فلورال وفاكهي',
 (SELECT id FROM public.categories WHERE slug='turkish-coffee'),
 ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
 'light',ARRAY['Specialty','Floral'],false,false,true,true,100),

-- ── Espresso ─────────────────────────────────────────────────────────────────────
('espresso-economy-crema','Economy Crema','الكريمة الاقتصادية',
 'Excellent crema and high strength, ideal for large volumes',
 'كريمة ممتازة وقوة عالية — للكميات الكبيرة والماكينات المكتبية',
 (SELECT id FROM public.categories WHERE slug='espresso'),
 ARRAY['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800'],
 'dark',ARRAY['Crema','Strong'],false,true,false,true,100),

('espresso-classic-italian','Classic Italian','الكلاسيك الإيطالي',
 'Chocolate and caramel with rich crema, best for cappuccino and latte',
 'شوكولاتة وكراميل، كريمة غنية — للكابتشينو واللاتيه',
 (SELECT id FROM public.categories WHERE slug='espresso'),
 ARRAY['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800'],
 'espresso',ARRAY['Chocolate','Caramel'],true,false,false,true,100),

('espresso-specialty-floral','Specialty Floral','الفلورال الـ Specialty',
 'Floral and fruity, best for direct espresso shots',
 'فلورال وفاكهي — للشوت المباشر',
 (SELECT id FROM public.categories WHERE slug='espresso'),
 ARRAY['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800'],
 'light',ARRAY['Floral','Fruity'],false,false,true,true,100),

('espresso-premium-vip','Premium VIP','بريميوم VIP',
 '90% arabica, golden crema, for 5-star hotels',
 'أرابيكا 90%، كريمة ذهبية — للفنادق 5 نجوم',
 (SELECT id FROM public.categories WHERE slug='espresso'),
 ARRAY['https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800'],
 'espresso',ARRAY['Premium','Arabica'],false,false,false,true,100),

-- ── Flavored Coffee (19 products) ────────────────────────────────────────────────
('flavored-coffee-hazelnut','Hazelnut Coffee','قهوة بندق',
 'Hazelnut flavored coffee','قهوة بنكهة البندق',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Hazelnut'],true,true,false,true,100),

('flavored-coffee-caramel','Caramel Coffee','قهوة كراميل',
 'Caramel flavored coffee','قهوة بنكهة الكراميل',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Caramel'],true,true,false,true,100),

('flavored-coffee-vanilla','Vanilla Coffee','قهوة فانيليا',
 'Vanilla flavored coffee','قهوة بنكهة الفانيليا',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Vanilla'],true,true,false,true,100),

('flavored-coffee-chocolate','Chocolate Coffee','قهوة شوكولاتة',
 'Chocolate flavored coffee','قهوة بنكهة الشوكولاتة',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Chocolate'],false,true,false,true,100),

('flavored-coffee-lotus','Lotus Coffee','قهوة لوتس',
 'Lotus flavored coffee','قهوة بنكهة اللوتس',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Lotus'],false,true,false,true,100),

('flavored-coffee-oreo','Oreo Coffee','قهوة أوريو',
 'Oreo flavored coffee','قهوة بنكهة الأوريو',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Oreo'],false,false,false,true,100),

('flavored-coffee-strawberry','Strawberry Coffee','قهوة فراولة',
 'Strawberry flavored coffee','قهوة بنكهة الفراولة',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Strawberry'],false,false,false,true,100),

('flavored-coffee-mocha','Mocha Coffee','قهوة موكا',
 'Mocha flavored coffee','قهوة بنكهة الموكا',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Mocha'],false,false,false,true,100),

('flavored-coffee-nutella','Nutella Coffee','قهوة نوتيلا',
 'Nutella flavored coffee','قهوة بنكهة النوتيلا',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Nutella'],false,false,false,true,100),

('flavored-coffee-cinnabon','Cinnabon Coffee','قهوة سينابون',
 'Cinnabon flavored coffee','قهوة بنكهة السينابون',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Cinnabon'],false,false,false,true,100),

('flavored-coffee-coconut','Coconut Coffee','قهوة جوز الهند',
 'Coconut flavored coffee','قهوة بنكهة جوز الهند',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Coconut'],false,false,false,true,100),

('flavored-coffee-banana','Banana Coffee','قهوة موز',
 'Banana flavored coffee','قهوة بنكهة الموز',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Banana'],false,false,false,true,100),

('flavored-coffee-mango','Mango Coffee','قهوة مانجو',
 'Mango flavored coffee','قهوة بنكهة المانجو',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Mango'],false,false,false,true,100),

('flavored-coffee-peach','Peach Coffee','قهوة خوخ',
 'Peach flavored coffee','قهوة بنكهة الخوخ',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Peach'],false,false,false,true,100),

('flavored-coffee-blueberry','Blueberry Coffee','قهوة توت',
 'Blueberry flavored coffee','قهوة بنكهة التوت',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Blueberry'],false,false,false,true,100),

('flavored-coffee-cherry','Cherry Coffee','قهوة كرز',
 'Cherry flavored coffee','قهوة بنكهة الكرز',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Cherry'],false,false,false,true,100),

('flavored-coffee-apple','Apple Coffee','قهوة تفاح',
 'Apple flavored coffee','قهوة بنكهة التفاح',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Apple'],false,false,false,true,100),

('flavored-coffee-grape','Grape Coffee','قهوة عنب',
 'Grape flavored coffee','قهوة بنكهة العنب',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Grape'],false,false,false,true,100),

('flavored-coffee-orange','Orange Coffee','قهوة برتقال',
 'Orange flavored coffee','قهوة بنكهة البرتقال',
 (SELECT id FROM public.categories WHERE slug='flavored-coffee'),
 ARRAY['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800'],
 'medium',ARRAY['Orange'],false,false,false,true,100),

-- ── Coffee Mix (12 products) ─────────────────────────────────────────────────────
('coffee-mix-original','Coffee Mix Original','كوفي ميكس أوريجنال',
 'Classic 3-in-1 coffee mix','كوفي ميكس كلاسيك 3 في 1',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY[]::text[],true,true,false,true,100),

('coffee-mix-hazelnut','Hazelnut Coffee Mix','كوفي ميكس بندق',
 'Hazelnut coffee mix','كوفي ميكس بندق',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Hazelnut'],true,false,false,true,100),

('coffee-mix-caramel','Caramel Coffee Mix','كوفي ميكس كراميل',
 'Caramel coffee mix','كوفي ميكس كراميل',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Caramel'],true,false,false,true,100),

('coffee-mix-vanilla','Vanilla Coffee Mix','كوفي ميكس فانيليا',
 'Vanilla coffee mix','كوفي ميكس فانيليا',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Vanilla'],false,false,false,true,100),

('coffee-mix-chocolate','Chocolate Coffee Mix','كوفي ميكس شوكولاتة',
 'Chocolate coffee mix','كوفي ميكس شوكولاتة',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Chocolate'],false,false,false,true,100),

('coffee-mix-lotus','Lotus Coffee Mix','كوفي ميكس لوتس',
 'Lotus coffee mix','كوفي ميكس لوتس',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Lotus'],false,false,false,true,100),

('coffee-mix-oreo','Oreo Coffee Mix','كوفي ميكس أوريو',
 'Oreo coffee mix','كوفي ميكس أوريو',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Oreo'],false,false,false,true,100),

('coffee-mix-strawberry','Strawberry Coffee Mix','كوفي ميكس فراولة',
 'Strawberry coffee mix','كوفي ميكس فراولة',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Strawberry'],false,false,false,true,100),

('coffee-mix-mocha','Mocha Coffee Mix','كوفي ميكس موكا',
 'Mocha coffee mix','كوفي ميكس موكا',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Mocha'],false,false,false,true,100),

('coffee-mix-nutella','Nutella Coffee Mix','كوفي ميكس نوتيلا',
 'Nutella coffee mix','كوفي ميكس نوتيلا',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Nutella'],false,false,false,true,100),

('coffee-mix-cinnabon','Cinnabon Coffee Mix','كوفي ميكس سينابون',
 'Cinnabon coffee mix','كوفي ميكس سينابون',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Cinnabon'],false,false,false,true,100),

('coffee-mix-coconut','Coconut Coffee Mix','كوفي ميكس جوز الهند',
 'Coconut coffee mix','كوفي ميكس جوز الهند',
 (SELECT id FROM public.categories WHERE slug='coffee-mix'),
 ARRAY['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800'],
 'medium',ARRAY['Coconut'],false,false,false,true,100),

-- ── Cappuccino (12 products) ─────────────────────────────────────────────────────
('cappuccino-original','Cappuccino Original','كابتشينو أوريجنال',
 'Classic creamy cappuccino','كابتشينو كلاسيك كريمي',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY[]::text[],true,true,false,true,100),

('cappuccino-hazelnut','Hazelnut Cappuccino','كابتشينو بندق',
 'Hazelnut cappuccino','كابتشينو بندق',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Hazelnut'],true,false,false,true,100),

('cappuccino-caramel','Caramel Cappuccino','كابتشينو كراميل',
 'Caramel cappuccino','كابتشينو كراميل',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Caramel'],true,false,false,true,100),

('cappuccino-vanilla','Vanilla Cappuccino','كابتشينو فانيليا',
 'Vanilla cappuccino','كابتشينو فانيليا',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Vanilla'],false,false,false,true,100),

('cappuccino-chocolate','Chocolate Cappuccino','كابتشينو شوكولاتة',
 'Chocolate cappuccino','كابتشينو شوكولاتة',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Chocolate'],false,false,false,true,100),

('cappuccino-lotus','Lotus Cappuccino','كابتشينو لوتس',
 'Lotus cappuccino','كابتشينو لوتس',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Lotus'],false,false,false,true,100),

('cappuccino-oreo','Oreo Cappuccino','كابتشينو أوريو',
 'Oreo cappuccino','كابتشينو أوريو',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Oreo'],false,false,false,true,100),

('cappuccino-strawberry','Strawberry Cappuccino','كابتشينو فراولة',
 'Strawberry cappuccino','كابتشينو فراولة',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Strawberry'],false,false,false,true,100),

('cappuccino-mocha','Mocha Cappuccino','كابتشينو موكا',
 'Mocha cappuccino','كابتشينو موكا',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Mocha'],false,false,false,true,100),

('cappuccino-nutella','Nutella Cappuccino','كابتشينو نوتيلا',
 'Nutella cappuccino','كابتشينو نوتيلا',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Nutella'],false,false,false,true,100),

('cappuccino-cinnabon','Cinnabon Cappuccino','كابتشينو سينابون',
 'Cinnabon cappuccino','كابتشينو سينابون',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Cinnabon'],false,false,false,true,100),

('cappuccino-coconut','Coconut Cappuccino','كابتشينو جوز الهند',
 'Coconut cappuccino','كابتشينو جوز الهند',
 (SELECT id FROM public.categories WHERE slug='cappuccino'),
 ARRAY['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800'],
 'medium',ARRAY['Coconut'],false,false,false,true,100),

-- ── Hot Chocolate (12 products) ──────────────────────────────────────────────────
('hot-chocolate-original','Hot Chocolate Original','هوت شوكلت أوريجنال',
 'Rich and creamy hot chocolate','هوت شوكلت غني وكريمي',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY[]::text[],true,true,false,true,100),

('hot-chocolate-hazelnut','Hazelnut Hot Chocolate','هوت شوكلت بندق',
 'Hazelnut hot chocolate','هوت شوكلت بندق',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Hazelnut'],true,false,false,true,100),

('hot-chocolate-caramel','Caramel Hot Chocolate','هوت شوكلت كراميل',
 'Caramel hot chocolate','هوت شوكلت كراميل',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Caramel'],true,false,false,true,100),

('hot-chocolate-vanilla','Vanilla Hot Chocolate','هوت شوكلت فانيليا',
 'Vanilla hot chocolate','هوت شوكلت فانيليا',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Vanilla'],false,false,false,true,100),

('hot-chocolate-chocolate','Chocolate Hot Chocolate','هوت شوكلت شوكولاتة',
 'Double chocolate hot chocolate','هوت شوكلت بنكهة الشوكولاتة المضاعفة',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Chocolate'],false,false,false,true,100),

('hot-chocolate-lotus','Lotus Hot Chocolate','هوت شوكلت لوتس',
 'Lotus hot chocolate','هوت شوكلت لوتس',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Lotus'],false,false,false,true,100),

('hot-chocolate-oreo','Oreo Hot Chocolate','هوت شوكلت أوريو',
 'Oreo hot chocolate','هوت شوكلت أوريو',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Oreo'],false,false,false,true,100),

('hot-chocolate-strawberry','Strawberry Hot Chocolate','هوت شوكلت فراولة',
 'Strawberry hot chocolate','هوت شوكلت فراولة',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Strawberry'],false,false,false,true,100),

('hot-chocolate-mocha','Mocha Hot Chocolate','هوت شوكلت موكا',
 'Mocha hot chocolate','هوت شوكلت موكا',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Mocha'],false,false,false,true,100),

('hot-chocolate-nutella','Nutella Hot Chocolate','هوت شوكلت نوتيلا',
 'Nutella hot chocolate','هوت شوكلت نوتيلا',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Nutella'],false,false,false,true,100),

('hot-chocolate-cinnabon','Cinnabon Hot Chocolate','هوت شوكلت سينابون',
 'Cinnabon hot chocolate','هوت شوكلت سينابون',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Cinnabon'],false,false,false,true,100),

('hot-chocolate-coconut','Coconut Hot Chocolate','هوت شوكلت جوز الهند',
 'Coconut hot chocolate','هوت شوكلت جوز الهند',
 (SELECT id FROM public.categories WHERE slug='hot-chocolate'),
 ARRAY['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800'],
 'medium',ARRAY['Coconut'],false,false,false,true,100)

ON CONFLICT (slug) DO UPDATE SET
  name_en        = EXCLUDED.name_en,
  name_ar        = EXCLUDED.name_ar,
  description_en = EXCLUDED.description_en,
  description_ar = EXCLUDED.description_ar,
  category_id    = EXCLUDED.category_id,
  images         = EXCLUDED.images,
  roast_level    = EXCLUDED.roast_level,
  flavor_notes   = EXCLUDED.flavor_notes,
  is_featured    = EXCLUDED.is_featured,
  is_best_seller = EXCLUDED.is_best_seller,
  is_new         = EXCLUDED.is_new,
  is_visible     = EXCLUDED.is_visible;


-- ─── PRODUCT SIZES ──────────────────────────────────────────────────────────────

INSERT INTO public.product_sizes (product_id, size, price, is_available)
VALUES
-- Turkish Coffee
((SELECT id FROM public.products WHERE slug='turkish-morning-strength'),   '250g', 125, true),
((SELECT id FROM public.products WHERE slug='turkish-morning-strength'),   '500g', 240, true),
((SELECT id FROM public.products WHERE slug='turkish-morning-strength'),   '1kg',  460, true),
((SELECT id FROM public.products WHERE slug='turkish-perfect-balance'),    '250g', 170, true),
((SELECT id FROM public.products WHERE slug='turkish-perfect-balance'),    '500g', 320, true),
((SELECT id FROM public.products WHERE slug='turkish-perfect-balance'),    '1kg',  600, true),
((SELECT id FROM public.products WHERE slug='turkish-professional-clean'), '250g', 200, true),
((SELECT id FROM public.products WHERE slug='turkish-professional-clean'), '500g', 380, true),
((SELECT id FROM public.products WHERE slug='turkish-professional-clean'), '1kg',  720, true),
((SELECT id FROM public.products WHERE slug='turkish-premium'),            '250g', 230, true),
((SELECT id FROM public.products WHERE slug='turkish-premium'),            '500g', 440, true),
((SELECT id FROM public.products WHERE slug='turkish-premium'),            '1kg',  840, true),

-- Espresso
((SELECT id FROM public.products WHERE slug='espresso-economy-crema'),    '250g', 135, true),
((SELECT id FROM public.products WHERE slug='espresso-economy-crema'),    '500g', 260, true),
((SELECT id FROM public.products WHERE slug='espresso-economy-crema'),    '1kg',  500, true),
((SELECT id FROM public.products WHERE slug='espresso-classic-italian'),  '250g', 200, true),
((SELECT id FROM public.products WHERE slug='espresso-classic-italian'),  '500g', 380, true),
((SELECT id FROM public.products WHERE slug='espresso-classic-italian'),  '1kg',  720, true),
((SELECT id FROM public.products WHERE slug='espresso-specialty-floral'), '250g', 210, true),
((SELECT id FROM public.products WHERE slug='espresso-specialty-floral'), '500g', 400, true),
((SELECT id FROM public.products WHERE slug='espresso-specialty-floral'), '1kg',  760, true),
((SELECT id FROM public.products WHERE slug='espresso-premium-vip'),      '250g', 255, true),
((SELECT id FROM public.products WHERE slug='espresso-premium-vip'),      '500g', 490, true),
((SELECT id FROM public.products WHERE slug='espresso-premium-vip'),      '1kg',  940, true),

-- Flavored Coffee (all 100/190/360)
((SELECT id FROM public.products WHERE slug='flavored-coffee-hazelnut'),   '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-hazelnut'),   '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-hazelnut'),   '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-caramel'),    '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-caramel'),    '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-caramel'),    '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-vanilla'),    '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-vanilla'),    '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-vanilla'),    '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-chocolate'),  '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-chocolate'),  '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-chocolate'),  '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-lotus'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-lotus'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-lotus'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-oreo'),       '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-oreo'),       '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-oreo'),       '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-strawberry'), '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-strawberry'), '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-strawberry'), '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mocha'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mocha'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mocha'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-nutella'),    '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-nutella'),    '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-nutella'),    '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cinnabon'),   '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cinnabon'),   '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cinnabon'),   '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-coconut'),    '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-coconut'),    '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-coconut'),    '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-banana'),     '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-banana'),     '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-banana'),     '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mango'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mango'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-mango'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-peach'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-peach'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-peach'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-blueberry'),  '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-blueberry'),  '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-blueberry'),  '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cherry'),     '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cherry'),     '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-cherry'),     '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-apple'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-apple'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-apple'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-grape'),      '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-grape'),      '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-grape'),      '1kg',  360, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-orange'),     '250g', 100, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-orange'),     '500g', 190, true),
((SELECT id FROM public.products WHERE slug='flavored-coffee-orange'),     '1kg',  360, true),

-- Coffee Mix: original 55/100/180 — flavors 65/120/220
((SELECT id FROM public.products WHERE slug='coffee-mix-original'),    '250g',  55, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-original'),    '500g', 100, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-original'),    '1kg',  180, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-hazelnut'),    '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-hazelnut'),    '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-hazelnut'),    '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-caramel'),     '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-caramel'),     '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-caramel'),     '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-vanilla'),     '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-vanilla'),     '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-vanilla'),     '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-chocolate'),   '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-chocolate'),   '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-chocolate'),   '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-lotus'),       '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-lotus'),       '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-lotus'),       '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-oreo'),        '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-oreo'),        '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-oreo'),        '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-strawberry'),  '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-strawberry'),  '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-strawberry'),  '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-mocha'),       '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-mocha'),       '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-mocha'),       '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-nutella'),     '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-nutella'),     '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-nutella'),     '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-cinnabon'),    '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-cinnabon'),    '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-cinnabon'),    '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-coconut'),     '250g',  65, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-coconut'),     '500g', 120, true),
((SELECT id FROM public.products WHERE slug='coffee-mix-coconut'),     '1kg',  220, true),

-- Cappuccino: original 65/120/220 — flavors 75/140/260
((SELECT id FROM public.products WHERE slug='cappuccino-original'),    '250g',  65, true),
((SELECT id FROM public.products WHERE slug='cappuccino-original'),    '500g', 120, true),
((SELECT id FROM public.products WHERE slug='cappuccino-original'),    '1kg',  220, true),
((SELECT id FROM public.products WHERE slug='cappuccino-hazelnut'),    '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-hazelnut'),    '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-hazelnut'),    '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-caramel'),     '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-caramel'),     '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-caramel'),     '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-vanilla'),     '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-vanilla'),     '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-vanilla'),     '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-chocolate'),   '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-chocolate'),   '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-chocolate'),   '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-lotus'),       '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-lotus'),       '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-lotus'),       '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-oreo'),        '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-oreo'),        '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-oreo'),        '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-strawberry'),  '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-strawberry'),  '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-strawberry'),  '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-mocha'),       '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-mocha'),       '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-mocha'),       '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-nutella'),     '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-nutella'),     '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-nutella'),     '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-cinnabon'),    '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-cinnabon'),    '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-cinnabon'),    '1kg',  260, true),
((SELECT id FROM public.products WHERE slug='cappuccino-coconut'),     '250g',  75, true),
((SELECT id FROM public.products WHERE slug='cappuccino-coconut'),     '500g', 140, true),
((SELECT id FROM public.products WHERE slug='cappuccino-coconut'),     '1kg',  260, true),

-- Hot Chocolate: original 60/110/200 — flavors 70/130/240
((SELECT id FROM public.products WHERE slug='hot-chocolate-original'),    '250g',  60, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-original'),    '500g', 110, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-original'),    '1kg',  200, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-hazelnut'),    '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-hazelnut'),    '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-hazelnut'),    '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-caramel'),     '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-caramel'),     '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-caramel'),     '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-vanilla'),     '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-vanilla'),     '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-vanilla'),     '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-chocolate'),   '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-chocolate'),   '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-chocolate'),   '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-lotus'),       '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-lotus'),       '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-lotus'),       '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-oreo'),        '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-oreo'),        '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-oreo'),        '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-strawberry'),  '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-strawberry'),  '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-strawberry'),  '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-mocha'),       '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-mocha'),       '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-mocha'),       '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-nutella'),     '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-nutella'),     '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-nutella'),     '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-cinnabon'),    '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-cinnabon'),    '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-cinnabon'),    '1kg',  240, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-coconut'),     '250g',  70, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-coconut'),     '500g', 130, true),
((SELECT id FROM public.products WHERE slug='hot-chocolate-coconut'),     '1kg',  240, true)

ON CONFLICT (product_id, size) DO UPDATE SET
  price        = EXCLUDED.price,
  is_available = EXCLUDED.is_available;
